#!/usr/bin/python

import pickle
import sys
%matplotlib inline
import matplotlib.pyplot
sys.path.append("../tools/")
from feature_format import featureFormat, targetFeatureSplit


### read in data dictionary, convert to numpy array
data_dict = pickle.load( open("../final_project/final_project_dataset.pkl", "r") )
features = ["salary", "bonus"]

###remove TOTAL outlier
data_dict.pop('TOTAL', 0)

data = featureFormat(data_dict, features)

for point in data:
    salary = point[0]
    bonus = point[1]
    matplotlib.pyplot.scatter( salary, bonus )

matplotlib.pyplot.xlabel("salary")
matplotlib.pyplot.ylabel("bonus")
matplotlib.pyplot.show()

### find two people that made bonuses of at least 5 million dollars, and a salary of over 1 million dollars
for name in data_dict:
    if data_dict[name]["salary"] != 'NaN' and data_dict[name]["bonus"] != 'NaN':
        if data_dict[name]["salary"] > 1000000 and data_dict[name]["bonus"] > 5000000:
            print name, data_dict[name]["bonus"], data_dict[name]["salary"]
